gestor_proyectos-main/config/routes.rb
Rails.application.routes.draw do
  root "formularies#index"
  resources :formularies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

gestor_proyectos-main/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

gestor_proyectos-main/app/models/formulary.rb
class Formulary < ApplicationRecord
    validates :name, presence: {message: "El campo name debe estar lleno!"} 
    validates :description, presence: {message: "El campo description debe estar lleno!"} 
    validates :condition, presence: {message: "El campo condition debe estar lleno!"} 
end

gestor_proyectos-main/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

gestor_proyectos-main/app/controllers/formularies_controller.rb
class FormulariesController < ApplicationController
  before_action :set_formulary, only: %i[ show edit update destroy ]

  # GET /formularies or /formularies.json
  def index
    @formularies = Formulary.all
  end

  # GET /formularies/1 or /formularies/1.json
  def show
  end

  # GET /formularies/new
  def new
    @formulary = Formulary.new
  end

  # GET /formularies/1/edit
  def edit
  end

  # POST /formularies or /formularies.json
  def create
    @formulary = Formulary.new(formulary_params)

    respond_to do |format|
      if @formulary.save
        format.html { redirect_to formulary_url(@formulary), notice: "Formulary was successfully created." }
        format.json { render :show, status: :created, location: @formulary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @formulary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formularies/1 or /formularies/1.json
  def update
    respond_to do |format|
      if @formulary.update(formulary_params)
        format.html { redirect_to formulary_url(@formulary), notice: "Formulary was successfully updated." }
        format.json { render :show, status: :ok, location: @formulary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @formulary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formularies/1 or /formularies/1.json
  def destroy
    @formulary.destroy

    respond_to do |format|
      format.html { redirect_to formularies_url, notice: "Formulary was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formulary
      @formulary = Formulary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def formulary_params
      params.require(:formulary).permit(:name, :description, :date_begin, :date_end, :condition)
    end
end

gestor_proyectos-main/app/helpers/application_helper.rb
module ApplicationHelper
end

gestor_proyectos-main/app/helpers/formularies_helper.rb
module FormulariesHelper
end

gestor_proyectos-main/app/views/formularies/_form.html.erb
<%= form_with(model: formulary) do |form| %>
  <% if formulary.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(formulary.errors.count, "error") %> prohibited this formulary from being saved:</h2>

      <ul>
        <% formulary.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :date_begin, style: "display: block" %>
    <%= form.date_field :date_begin %>
  </div>

  <div>
    <%= form.label :date_end, style: "display: block" %>
    <%= form.date_field :date_end %>
  </div>

  <div>
    <%= form.label :condition, style: "display: block" %>
    <%= form.text_field :condition %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

gestor_proyectos-main/app/views/formularies/_formulary.html.erb
<div id="<%= dom_id formulary %>">
  <p>
    <strong>Name:</strong>
    <%= formulary.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= formulary.description %>
  </p>

  <p>
    <strong>Date begin:</strong>
    <%= formulary.date_begin %>
  </p>

  <p>
    <strong>Date end:</strong>
    <%= formulary.date_end %>
  </p>

  <p>
    <strong>Condition:</strong>
    <%= formulary.condition %>
  </p>

</div>

gestor_proyectos-main/app/views/formularies/edit.html.erb
<h1>Editing formulary</h1>

<%= render "form", formulary: @formulary %>

<br>

<div>
  <%= link_to "Show this formulary", @formulary %> |
  <%= link_to "Back to formularies", formularies_path %>
</div>

gestor_proyectos-main/app/views/formularies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Formularies</h1>

<div id="formularies">
  <% @formularies.each do |formulary| %>
    <%= render formulary %>
    <p>
      <%= link_to "Show this formulary", formulary %>
    </p>
  <% end %>
</div>

<%= link_to "New formulary", new_formulary_path %>

gestor_proyectos-main/app/views/formularies/new.html.erb
<h1>New formulary</h1>

<%= render "form", formulary: @formulary %>

<br>

<div>
  <%= link_to "Back to formularies", formularies_path %>
</div>

gestor_proyectos-main/app/views/formularies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @formulary %>

<div>
  <%= link_to "Edit this formulary", edit_formulary_path(@formulary) %> |
  <%= link_to "Back to formularies", formularies_path %>

  <%= button_to "Destroy this formulary", @formulary, method: :delete %>
</div>

gestor_proyectos-main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
  <!-- https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css -->
  
  <title>Gestor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <!-- Image and text -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2frJbAPQz8G4NQhVyysWYUEohH_xXG4OymA&usqp=CAU" width="30" height="30" class="d-inline-block align-top" alt="">
    Gestor de proyectos
  </a>
</nav>

    <%= yield %>

    </body>
</html>